feat: merge upstream node-soap (#2)
* Fixed some issues with xsd elements (#1057)

* Fixed some issues with xsd elements

* Made the fix more specific to the particular usecase

* Added a test for aliased namespaces

* Release v0.27.0

* Move @types/request to dependencies (#1059)

soap's d.ts files depend on request. Unfortunately, since request
doesn't ship its own types, that means consumers of soap also need
@types/request. Currently @types/request is just a dev dependency, which
doesn't get installed by `npm install`. The fix is to move
`@types/request` to the dependencies list.

The error looks like this:

```
node_modules/soap/lib/client.d.ts(4,26): error TS7016: Could not find a declaration file for module 'request'. '../../../tests/cases/user/soap/node_modules/request/index.js' implicitly has an 'any' type.
```

Note that this only shows up when consumers compile with --strict, which is
fairly common.  Typescript's user-code tests include soap and detected
it after 0.27 shipped.

* Release v0.27.1

* Updated read me to reflect changes in soap.listen (#1060)

* Updated Read.me to reflect changes in soap.listen

* Updated Readme.md

* Updated Readme.md

* Updated Readme.md

* types: move forceSoap12Headers to IWsdlBaseOptions (#1063)

"forceSoap12Headers" works on server since bcc41e6. So, this option
should be available to server as well.

* client.addSoapHeader() dynamic SOAP header (#1062)

* Added support for parsing of doubles and floats. (#1065)

* Added support for parsing of doubles and floats.
package-lock updated due to out-of-date version.

* Reverting changed package-lock file.